// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkwevzsqolnkczfscbak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indrd2V2enNxb2xua2N6ZnNjYmFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NjAyNzcsImV4cCI6MjA3MDMzNjI3N30.EV1aVrE-TMWr4UUVre-MEwtQV_QcFxJgYAPXU6oWwHI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});